name    'brutus333-hiera_roleprofile'
version '0.0.1'
author 'brutus333'
license 'Apache License, Version 2.0'
summary 'A Hiera Yaml backend with dynamic hierarchies'
description ' Hiera is a configuration data store with pluggable back ends; hiera-roleprofile is a yaml backend that build a dynamic hierarchy based on the role&profile classes assigned to the node.'
project_page 'https://github.com/brutus333/hiera_roleprofile'
source 'git://github.com/brutus333/hiera_roleprofile.git'
